language: node_js
node_js:
  - 11
dist: trusty
env:
 - IMAGE_NAME=571100653727.dkr.ecr.eu-west-1.amazonaws.com/juiceshop:1.0-$TRAVIS_BUILD_NUMBER

#install: if [ -z "$TRAVIS_TAG" ]; then npm install; fi
#script: if [ -z "$TRAVIS_TAG" ]; then NODE_ENV=test npm test; fi
before_deploy:
  - rm -rf node_modules
  - rm -rf frontend/node_modules
  - npm install --production
  - npm run package
addons:
  sonarcloud:
    organization: "mistermania-github" # the key of the org you chose at step #3
    token:
      secure: "b7c3948ac08daa505110503fc8240b55a684544b" # encrypted value of your token
  artifacts:
    s3_region: "eu-west-1"
    paths:
      - ./reportD
after_success:
  - pip install --user awscli
  - eval $(aws ecr get-login --region eu-west-1 --no-include-email)
  - wget https://bintray.com/jeremy-long/owasp/download_file?file_path=dependency-check-5.0.0-M3-release.zip
  - wget https://github.com/optiopay/klar/releases/download/v2.4.0/klar-2.4.0-linux-amd64
  - unzip download_file?file_path=dependency-check-5.0.0-M3-release.zip
  - sh ./dependency-check/bin/dependency-check.sh --out reportD --scan .
  - docker build -t 3r1co/nodetest .
  - docker tag 3r1co/nodetest $IMAGE_NAME
  - docker push $IMAGE_NAME
  - aws cloudformation deploy --template-file ./ecs-task.yaml --stack-name ecs-deployment --region eu-west-1 --parameter-override ImageName=$IMAGE_NAME
  - aws cloudformation update-stack --template-body file://./ecs-task.yaml --stack-name ecs-deployment --region eu-west-1 --parameters "ParameterKey=ImageName,ParameterValue=$IMAGE_NAME"
  - sonar-scanner -Dsonar.projectKey=mistermania_juice-shop -Dsonar.organization=mistermania-github -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=df2cb62fc5792eb831485b37f0b93948071ac446 -Dsonar.javascript.lcov.reportPaths=./build/reports/coverage/server-tests/lcov.info,./build/reports/coverage/api-tests
  - DOCKER_LOGIN=`aws ecr get-login --no-include-email`
  - PASSWORD=`echo $DOCKER_LOGIN | cut -d' ' -f6`
  - REGISTRY=`echo $DOCKER_LOGIN | cut -d' ' -f7 | sed "s/https:\/\///"`
  - DOCKER_USER=AWS DOCKER_PASSWORD=${PASSWORD} ./klar-2.4.0-linux-amd64 $IMAGE_NAME
